// solid-demo/src/SetOfFields.tsx
import { Component } from "solid-js";
import SingleField from "./SingleField";

interface SingleFieldProperties {
  index: number;
  value1: string;
  value2: string;
  value3: string;
}

const SetOfFields: Component<SingleFieldProperties> = (props: SingleFieldProperties ) => {

  console.log(`SetOfFields ${props.index} recalc`);
  return (
    <div>
      <SingleField index={props.index*10+1} value={props.value1} />
      <SingleField index={props.index*10+2} value={props.value2} />
      <SingleField index={props.index*10+3} value={props.value3} />
    </div>
  );
};

export default SetOfFields;

// react-redux-demo/src/SetOfFields.tsx
import React, { FC, useEffect, useState } from "react";
import { RootState } from "./store";
import GroupedField from "./GroupedField";

interface SingleFieldProperties {
  index: number;
  field1: number;
  field2: number;
  field3: number;
}

const SetOfFields: FC<SingleFieldProperties> = ({index, field1,field2,field3}) => {
  console.log(`SetOfFields ${index} recalc`);

  const fieldGetter = (state: RootState, field: number) => {
    const valuesObject: any = state.values;
    return valuesObject[`field${field}`] as string;
  }

  return (
    <div>
      <GroupedField index={index*10+1} getter={state => fieldGetter(state, field1)} />
      <GroupedField index={index*10+2} getter={state => fieldGetter(state, field2)} />
      <GroupedField index={index*10+3} getter={state => fieldGetter(state, field3)} />
    </div>
  );
};

export default SetOfFields;
