// react-demo/src/SingleField.tsx
import React, { FC } from "react";

interface SingleFieldProperties {
  index: number;
  value: string;
}

const SingleField: FC<SingleFieldProperties> = ({index, value}) => {

  console.log(`SingleField-${index} recalc`);
  return (
    <div>
      <p>{index}={value}</p>
    </div>
  );
};

export default SingleField;

// solid-demo/src/SingleField.tsx
import { Component } from "solid-js";

interface SingleFieldProperties {
  index: number;
  value: string;
}

const SingleField: Component<SingleFieldProperties> = (props: SingleFieldProperties) => {

  console.log(`SingleField-${props.index} recalc`);
  return (
    <div>
      <p>{props.index}={props.value}</p>
    </div>
  );
};

export default SingleField;
